[package]
name = "can-type-rs"
version = "0.1.0"
edition = "2021"
authors = ["zhuyu <zhuyu4839@gmail.com>"]
keywords = ["can", "j1939"]
license = "GPL-3.0"
description = "CAN type define."
homepage = "https://github.com/zhuyu4839/can-type-rs"
repository = "https://github.com/zhuyu4839/can-type-rs"
readme = "README.md"

[dependencies]
bitflags = "2"
bitfield-struct = "0"
